### ISSUE TITLE
I have a question about the comparison to genome ratio after single cell sequencing and spatial group sequencing

### ISSUE THREAD

**Issue by WangHaoPlan** [yangteam/Spatiotemporal-transcriptomic-atlas-of-planarian-regeneration#1]
hi，i am a student who is very interested in planarian regeneration. i have a question about the comparison to genome ratio after single cell sequencing and spatial group sequencing. Recently i compared your single cell data to dd-g4-genome(2018-nature),but the comparison rate of reading maps to the genome is only 40%. I would like to know the approximate comparison rate of your data analysis. Can you help me？

**Comment by yangteam** [comment]
Hello, for ST data, the mapping ratio is around 70% and for sc-RNA-seq data around 40%~50%.

**Comment by WangHaoPlan** [comment]
oh，Thank you very much for your reply！

**Comment by yangteam** [comment]
It’s my pleasure.
